package Figuras;

/**
 *
 * @author USUARIO
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCradio = new javax.swing.JTextField();
        txtCarea = new javax.swing.JTextField();
        txtCperimetro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnArea = new javax.swing.JButton();
        btnPerimetro = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnCuadradoArea = new javax.swing.JButton();
        btnCuadradoPerimetro = new javax.swing.JButton();
        btnCuadradoBorrar = new javax.swing.JButton();
        txtCuadradoLado = new javax.swing.JTextField();
        txtCuadradoArea = new javax.swing.JTextField();
        txtCuadradoPerimetro = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtRectanguloBase = new javax.swing.JTextField();
        txtRectanguloAltura = new javax.swing.JTextField();
        txtRectanguloArea = new javax.swing.JTextField();
        txtRectanguloPerimetro = new javax.swing.JTextField();
        btnRectanguloArea = new javax.swing.JButton();
        btnRectanguloPerimetro = new javax.swing.JButton();
        btnRectanguloBorrar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtTrBase = new javax.swing.JTextField();
        txtTrAltura = new javax.swing.JTextField();
        txtTrArea = new javax.swing.JTextField();
        txtTrPerimetro = new javax.swing.JTextField();
        txtTrHipotenusa = new javax.swing.JTextField();
        txtTrTipo = new javax.swing.JTextField();
        btnTrArea = new javax.swing.JButton();
        btnTrPerimetro = new javax.swing.JButton();
        btnTrHipotenusa = new javax.swing.JButton();
        btnTrBorrar = new javax.swing.JButton();
        btnTrTipo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Radio");

        jLabel2.setText("Area");

        jLabel3.setText("Perimetro");

        jLabel4.setText("Círculo");

        btnArea.setText("Calcular Área");
        btnArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaActionPerformed(evt);
            }
        });

        btnPerimetro.setText("Calcular Perímetro");
        btnPerimetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerimetroActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        jLabel5.setText("Cuadrado");

        jLabel6.setText("Lado");

        jLabel7.setText("Área");

        jLabel8.setText("Perímetro");

        btnCuadradoArea.setText("Calcular Área");
        btnCuadradoArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuadradoAreaActionPerformed(evt);
            }
        });

        btnCuadradoPerimetro.setText("Calcular Perímetro");
        btnCuadradoPerimetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuadradoPerimetroActionPerformed(evt);
            }
        });

        btnCuadradoBorrar.setText("Borrar");
        btnCuadradoBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuadradoBorrarActionPerformed(evt);
            }
        });

        jLabel9.setText("Rectangulo");

        jLabel10.setText("Base");

        jLabel11.setText("Altura");

        jLabel12.setText("Área");

        jLabel13.setText("Perímetro");

        txtRectanguloArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRectanguloAreaActionPerformed(evt);
            }
        });

        btnRectanguloArea.setText("Calcular Área");
        btnRectanguloArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRectanguloAreaActionPerformed(evt);
            }
        });

        btnRectanguloPerimetro.setText("Calcular Perímetro");
        btnRectanguloPerimetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRectanguloPerimetroActionPerformed(evt);
            }
        });

        btnRectanguloBorrar.setText("Borrar");
        btnRectanguloBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRectanguloBorrarActionPerformed(evt);
            }
        });

        jLabel14.setText("Triangulo Rectangulo");

        jLabel15.setText("Base");

        jLabel16.setText("Altura");

        jLabel17.setText("Area");

        jLabel18.setText("Perímetro");

        jLabel19.setText("Hipotenusa");

        jLabel20.setText("Tipo Triángulo");

        btnTrArea.setText("Calcular Área");
        btnTrArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrAreaActionPerformed(evt);
            }
        });

        btnTrPerimetro.setText("Calcular Perímetro");
        btnTrPerimetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrPerimetroActionPerformed(evt);
            }
        });

        btnTrHipotenusa.setText("Calcular Hipotenusa");
        btnTrHipotenusa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrHipotenusaActionPerformed(evt);
            }
        });

        btnTrBorrar.setText("Borrar");
        btnTrBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrBorrarActionPerformed(evt);
            }
        });

        btnTrTipo.setText("Tipo Triángulo");
        btnTrTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrTipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(392, 392, 392))
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jLabel9)
                .addGap(145, 970, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCradio, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCarea, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCperimetro, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtRectanguloAltura, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                        .addComponent(txtRectanguloArea))
                                    .addComponent(txtRectanguloBase, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnArea)
                                    .addComponent(btnRectanguloArea))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnPerimetro)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnBorrar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(btnRectanguloPerimetro)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnRectanguloBorrar)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCuadradoArea)
                                .addGap(34, 34, 34)
                                .addComponent(btnCuadradoPerimetro)
                                .addGap(18, 18, 18)
                                .addComponent(btnCuadradoBorrar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCuadradoPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtCuadradoArea)
                                        .addComponent(txtCuadradoLado, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(txtRectanguloPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtTrHipotenusa)
                        .addComponent(txtTrArea)
                        .addComponent(txtTrAltura)
                        .addComponent(txtTrBase)
                        .addComponent(txtTrPerimetro)
                        .addComponent(txtTrTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel14))
                .addGap(106, 106, 106))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnTrArea)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTrPerimetro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTrHipotenusa)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnTrTipo)
                        .addGap(57, 57, 57)
                        .addComponent(btnTrBorrar)
                        .addGap(138, 138, 138))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel4)
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(30, 30, 30)
                                    .addComponent(jLabel2)
                                    .addGap(26, 26, 26)
                                    .addComponent(jLabel3))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtCradio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6))
                                    .addGap(24, 24, 24)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtCarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7))
                                    .addGap(20, 20, 20)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtCperimetro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCuadradoLado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(txtCuadradoArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtCuadradoPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnArea)
                            .addComponent(btnPerimetro)
                            .addComponent(btnBorrar)
                            .addComponent(btnCuadradoArea)
                            .addComponent(btnCuadradoPerimetro)
                            .addComponent(btnCuadradoBorrar))
                        .addGap(45, 45, 45)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtRectanguloBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(txtRectanguloAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(txtRectanguloArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel11)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel12)
                                .addGap(28, 28, 28)
                                .addComponent(txtRectanguloPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnRectanguloBorrar)
                                    .addComponent(btnRectanguloPerimetro)
                                    .addComponent(btnRectanguloArea))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addGap(20, 20, 20)
                                        .addComponent(jLabel16)
                                        .addGap(45, 45, 45))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtTrBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtTrAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel17)
                                            .addComponent(txtTrArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTrPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTrHipotenusa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(txtTrTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTrHipotenusa)
                    .addComponent(btnTrPerimetro)
                    .addComponent(btnTrArea))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTrBorrar)
                    .addComponent(btnTrTipo))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>                        

    private void btnAreaActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        double area;
        int radio = Integer.parseInt(txtCradio.getText());
        Circulo figura1 = new Circulo(radio);
        area = figura1.calcularArea() ;
        txtCarea.setText(String.valueOf(area));
    }                                       

    private void btnPerimetroActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        double perimetro;
        int radio = Integer.parseInt(txtCradio.getText());
        Circulo figura1 = new Circulo(radio);
        perimetro = figura1.calcularPerimetro();
        txtCperimetro.setText(String.valueOf(perimetro));
    }                                            

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        txtCarea.setText("");
        txtCperimetro.setText("");
        txtCradio.setText("");
    }                                         

    private void btnCuadradoAreaActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
        double area;
        int lado = Integer.parseInt(txtCuadradoLado.getText());
        Cuadrado figura3 = new Cuadrado(lado);
        area = figura3.calcularArea() ;
        txtCuadradoArea.setText(String.valueOf(area));
        
    }                                               

    private void btnCuadradoPerimetroActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        // TODO add your handling code here:
        double perimetro;
        int lado = Integer.parseInt(txtCuadradoLado.getText());
        Cuadrado figura3 = new Cuadrado(lado);
        perimetro = figura3.calcularPerimetro() ;
        txtCuadradoPerimetro.setText(String.valueOf(perimetro));
    }                                                    

    private void btnCuadradoBorrarActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
        txtCuadradoArea.setText("");
        txtCuadradoPerimetro.setText("");
        txtCuadradoLado.setText("");
    }                                                 

    private void txtRectanguloAreaActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 

    private void btnRectanguloAreaActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
        double area;
        int base_rectangulo = Integer.parseInt(txtRectanguloBase.getText());
        int altura_rectangulo = Integer.parseInt(txtRectanguloAltura.getText());
        Rectangulo figura2 = new Rectangulo(base_rectangulo,altura_rectangulo);
        area = figura2.calcularArea();
        txtRectanguloArea.setText(String.valueOf(area));
    }                                                 

    private void btnRectanguloPerimetroActionPerformed(java.awt.event.ActionEvent evt) {                                                       
        // TODO add your handling code here:
        double perimetro;
        int base_rectangulo = Integer.parseInt(txtRectanguloBase.getText());
        int altura_rectangulo = Integer.parseInt(txtRectanguloAltura.getText());
        Rectangulo figura2 = new Rectangulo(base_rectangulo,altura_rectangulo);
        perimetro = figura2.calcularPerimetro();
        txtRectanguloPerimetro.setText(String.valueOf(perimetro));
    }                                                      

    private void btnRectanguloBorrarActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
        txtRectanguloArea.setText("");
        txtRectanguloPerimetro.setText("");
        txtRectanguloBase.setText("");
        txtRectanguloAltura.setText("");
    }                                                   

    private void btnTrAreaActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        double area;
        int base_triangulorectangulo = Integer.parseInt(txtTrBase.getText());
        int altura_triangulorectangulo = Integer.parseInt(txtTrAltura.getText());
        TrianguloRectangulo figura4 = new TrianguloRectangulo(base_triangulorectangulo,altura_triangulorectangulo);
        area = figura4.calcularArea();
        txtTrArea.setText(String.valueOf(area));
    }                                         

    private void btnTrPerimetroActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
        double perimetro;
        int base_triangulorectangulo = Integer.parseInt(txtTrBase.getText());
        int altura_triangulorectangulo = Integer.parseInt(txtTrAltura.getText());
        TrianguloRectangulo figura4 = new TrianguloRectangulo(base_triangulorectangulo,altura_triangulorectangulo);
        perimetro = figura4.calcularPerimetro();
        txtTrPerimetro.setText(String.valueOf(perimetro));
    }                                              

    private void btnTrHipotenusaActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
        double hipotenusa;
        int base_triangulorectangulo = Integer.parseInt(txtTrBase.getText());
        int altura_triangulorectangulo = Integer.parseInt(txtTrAltura.getText());
        TrianguloRectangulo figura4 = new TrianguloRectangulo(base_triangulorectangulo,altura_triangulorectangulo);
        hipotenusa = figura4.calcularHipotenusa();
        txtTrHipotenusa.setText(String.valueOf(hipotenusa));
    }                                               

    private void btnTrBorrarActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        txtTrArea.setText("");
        txtTrBase.setText("");
        txtTrAltura.setText("");
        txtTrPerimetro.setText("");
        txtTrHipotenusa.setText("");
        txtTrTipo.setText("");
    }                                           

    private void btnTrTipoActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnArea;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCuadradoArea;
    private javax.swing.JButton btnCuadradoBorrar;
    private javax.swing.JButton btnCuadradoPerimetro;
    private javax.swing.JButton btnPerimetro;
    private javax.swing.JButton btnRectanguloArea;
    private javax.swing.JButton btnRectanguloBorrar;
    private javax.swing.JButton btnRectanguloPerimetro;
    private javax.swing.JButton btnTrArea;
    private javax.swing.JButton btnTrBorrar;
    private javax.swing.JButton btnTrHipotenusa;
    private javax.swing.JButton btnTrPerimetro;
    private javax.swing.JButton btnTrTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCarea;
    private javax.swing.JTextField txtCperimetro;
    private javax.swing.JTextField txtCradio;
    private javax.swing.JTextField txtCuadradoArea;
    private javax.swing.JTextField txtCuadradoLado;
    private javax.swing.JTextField txtCuadradoPerimetro;
    private javax.swing.JTextField txtRectanguloAltura;
    private javax.swing.JTextField txtRectanguloArea;
    private javax.swing.JTextField txtRectanguloBase;
    private javax.swing.JTextField txtRectanguloPerimetro;
    private javax.swing.JTextField txtTrAltura;
    private javax.swing.JTextField txtTrArea;
    private javax.swing.JTextField txtTrBase;
    private javax.swing.JTextField txtTrHipotenusa;
    private javax.swing.JTextField txtTrPerimetro;
    private javax.swing.JTextField txtTrTipo;
    // End of variables declaration                   
}

